"""add user_id and is_active in watchlist(table)

Revision ID: 84d8efd64ea6
Revises: da0e10b86bb6
Create Date: 2026-05-14 23:11:24.300372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d8efd64ea6'
down_revision: Union[str, Sequence[str], None] = 'da0e10b86bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('watchlist', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'watchlist', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.drop_column('watchlist', 'is_active')
    op.drop_column('watchlist', 'user_id')
    # ### end Alembic commands ###
