"""add is_active to reviews

Revision ID: a3d7ed82e788
Revises: 93d4c32d3cc6
Create Date: 2026-05-17 19:23:20.183906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d7ed82e788'
down_revision: Union[str, Sequence[str], None] = '93d4c32d3cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_active')
    # ### end Alembic commands ###
