"""add is_active in LikeModel

Revision ID: d386de5837a6
Revises: a3d7ed82e788
Create Date: 2026-05-17 22:25:43.085926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd386de5837a6'
down_revision: Union[str, Sequence[str], None] = 'a3d7ed82e788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'is_active')
    # ### end Alembic commands ###
