"""fix_password_length

Revision ID: da0e10b86bb6
Revises: 220344aaa800
Create Date: 2026-05-12 15:42:24.176294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0e10b86bb6'
down_revision: Union[str, Sequence[str], None] = '220344aaa800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.String(50),
                    type_=sa.String(255),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.String(255),
                    type_=sa.String(50),
                    nullable=False)
    # ### end Alembic commands ###

